import { useEffect, useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getApiErrorMessage } from '@san/shared';
import type { TilJobTone, TilPageLogic } from '../types';
import {
  useTilDeleteMutation,
  useTilGenerateMutation,
  useTilGithubCommitMutation,
  useTilUpdateMutation,
} from './useTilMutations';
import type { TilResponse } from '@san/shared';
import {
  tilKeys,
  useTilAsyncJobStatus,
  useTilByDate,
  useTilRecallCards,
  useTilSources,
} from './useTilQueries';

const EMPTY_TIL_LIST: TilResponse[] = [];
const AUTO_TIL_POLL_INTERVAL_MS = 2000;
const AUTO_TIL_POLL_TIMEOUT_MS = 60000;
const TIL_GENERATION_JOB_STORAGE_PREFIX = 'san:til-generation-job';
const SESSION_ID_STORAGE_KEY = 'san_session_id';
const DUPLICATE_TIL_GENERATION_MESSAGE = '\uC774\uBBF8 TIL \uC0DD\uC131\uC774 \uC9C4\uD589 \uC911\uC785\uB2C8\uB2E4.';
const TIL_GENERATION_ERROR_MESSAGES = {
  DUPLICATE_RESOURCE: DUPLICATE_TIL_GENERATION_MESSAGE,
  DUPLICATE_TIL_GENERATION: DUPLICATE_TIL_GENERATION_MESSAGE,
};

export function useTilPageLogic(): TilPageLogic {
  const queryClient = useQueryClient();
  const [selectedDate, setSelectedDate] = useState(() => getInitialSelectedDate());
  const [latestAutoGeneratedTilDate, setLatestAutoGeneratedTilDate] = useState(() => getLatestAutoGeneratedTilDate());
  const [autoTilPollStartedAt, setAutoTilPollStartedAt] = useState<number | null>(null);
  const [autoTilPollTimedOut, setAutoTilPollTimedOut] = useState(false);
  const [selectedSummaryId, setSelectedSummaryId] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [draft, setDraft] = useState('');
  const [generationJobId, setGenerationJobId] = useState<string | null>(() => getStoredGenerationJobId(selectedDate));
  const [commitJobId, setCommitJobId] = useState<string | null>(null);
  const [prevSelectedDate, setPrevSelectedDate] = useState(selectedDate);
  const [prevSelectedSummaryId, setPrevSelectedSummaryId] = useState<string | null | undefined>(null);

  const tilQuery = useTilByDate(selectedDate, {
    refetchInterval: (query) => {
      const tilList = query.state.data;
      const isLatestAutoDate = selectedDate === latestAutoGeneratedTilDate;
      if (!isLatestAutoDate || autoTilPollTimedOut || !tilList || tilList.length > 0) return false;
      return AUTO_TIL_POLL_INTERVAL_MS;
    },
  });

  const tilList = tilQuery.data ?? EMPTY_TIL_LIST;
  const hasLoadedSelectedDate = Array.isArray(tilQuery.data);
  const selectedTil = useMemo(
    () => {
      if (!hasLoadedSelectedDate) return null;
      return tilList.find((item) => item.summaryId === selectedSummaryId) ?? tilList[0] ?? null;
    },
    [hasLoadedSelectedDate, selectedSummaryId, tilList],
  );

  useEffect(() => {
    const timeoutId = window.setTimeout(() => {
      const nextLatestAutoDate = getLatestAutoGeneratedTilDate();
      setLatestAutoGeneratedTilDate(nextLatestAutoDate);
      setSelectedDate((currentDate) => currentDate === latestAutoGeneratedTilDate ? nextLatestAutoDate : currentDate);
    }, getMillisecondsUntilNextTilBoundary());

    return () => window.clearTimeout(timeoutId);
  }, [latestAutoGeneratedTilDate]);

  useEffect(() => {
    setAutoTilPollStartedAt(null);
    setAutoTilPollTimedOut(false);
  }, [selectedDate]);

  useEffect(() => {
    const isLatestAutoDate = selectedDate === latestAutoGeneratedTilDate;
    if (!isLatestAutoDate || !tilQuery.data || tilQuery.data.length > 0) return;
    setAutoTilPollStartedAt((current) => current ?? Date.now());
  }, [latestAutoGeneratedTilDate, selectedDate, tilQuery.data]);

  useEffect(() => {
    if (!autoTilPollStartedAt || selectedDate !== latestAutoGeneratedTilDate || tilList.length > 0) return undefined;

    const timeoutId = window.setTimeout(() => {
      setAutoTilPollTimedOut(true);
    }, AUTO_TIL_POLL_TIMEOUT_MS);

    return () => window.clearTimeout(timeoutId);
  }, [autoTilPollStartedAt, latestAutoGeneratedTilDate, selectedDate, tilList.length]);

  if (selectedDate !== prevSelectedDate) {
    setPrevSelectedDate(selectedDate);
    setSelectedSummaryId(null);
    setGenerationJobId(getStoredGenerationJobId(selectedDate));
    setCommitJobId(null);
  }

  if (selectedTil?.summaryId !== prevSelectedSummaryId) {
    setPrevSelectedSummaryId(selectedTil?.summaryId);
    setTitle(selectedTil?.title ?? '');
    setDraft(selectedTil?.content ?? '');
  }

  const recallCardsQuery = useTilRecallCards(selectedTil?.summaryId);
  const sourcesQuery = useTilSources(selectedTil?.summaryId);
  const generationStatusQuery = useTilAsyncJobStatus(generationJobId);
  const commitStatusQuery = useTilAsyncJobStatus(commitJobId);

  useEffect(() => {
    const generationStatus = generationStatusQuery.data?.status;
    if (generationStatus === 'COMPLETED') {
      void queryClient.invalidateQueries({ queryKey: tilKeys.byDate(selectedDate) });
      if (selectedSummaryId) {
        void queryClient.invalidateQueries({ queryKey: tilKeys.recallCards(selectedSummaryId) });
        void queryClient.invalidateQueries({ queryKey: tilKeys.recallQuizzes(selectedDate, 'OX') });
        void queryClient.invalidateQueries({ queryKey: tilKeys.recallQuizzes(selectedDate, 'SHORT_ANSWER') });
      }
    }

    if (generationStatus === 'COMPLETED' || generationStatus === 'FAILED') {
      clearStoredGenerationJobId(selectedDate);
    }
  }, [generationStatusQuery.data?.status, queryClient, selectedDate, selectedSummaryId]);

  const generateMutation = useTilGenerateMutation({
    targetDate: selectedDate,
    onSuccess: (response) => {
      storeGenerationJobId(response.targetDate, response.jobId);
      setGenerationJobId(response.targetDate === selectedDate ? response.jobId : getStoredGenerationJobId(selectedDate));
      setSelectedSummaryId(response.summaryId);
    },
  });

  const updateMutation = useTilUpdateMutation({
    onSuccess: (response) => {
      setSelectedSummaryId(response.summaryId);
      setTitle(response.title ?? '');
      setDraft(response.content ?? '');
      queryClient.setQueryData<TilResponse[]>(tilKeys.byDate(response.targetDate), (previous) => {
        if (!previous) return [response];
        return previous.map((item) => item.summaryId === response.summaryId ? response : item);
      });
      void queryClient.invalidateQueries({ queryKey: tilKeys.recallCards(response.summaryId) });
      void queryClient.invalidateQueries({ queryKey: tilKeys.recallQuizzes(response.targetDate, 'OX') });
      void queryClient.invalidateQueries({ queryKey: tilKeys.recallQuizzes(response.targetDate, 'SHORT_ANSWER') });
    },
  });

  const deleteMutation = useTilDeleteMutation({
    onSuccess: (_response, deletedSummaryId) => {
      const remaining = tilList.filter((item) => item.summaryId !== deletedSummaryId);
      const nextTil = remaining[0] ?? null;

      setSelectedSummaryId(nextTil?.summaryId ?? null);
      setTitle(nextTil?.title ?? '');
      setDraft(nextTil?.content ?? '');
      queryClient.setQueryData<TilResponse[]>(tilKeys.byDate(selectedDate), remaining);
      void queryClient.invalidateQueries({ queryKey: tilKeys.byDate(selectedDate) });
    },
  });

  const commitMutation = useTilGithubCommitMutation({
    onSuccess: (response) => {
      setCommitJobId(response.jobId);
    },
  });

  const generationTone = getJobTone(
    generationJobId,
    generationStatusQuery.data?.status,
    generateMutation.isPending || generationStatusQuery.isFetching,
    generateMutation.isError || generationStatusQuery.data?.status === 'FAILED',
  );
  const commitTone = getJobTone(
    commitJobId,
    commitStatusQuery.data?.status,
    commitMutation.isPending,
    commitMutation.isError || commitStatusQuery.data?.status === 'FAILED',
  );

  const generationMessage = getGenerationMessage(
    generationJobId,
    generationStatusQuery.data?.status,
    generationStatusQuery.data?.errorMessage,
    generateMutation.error,
  );

  const commitMessage = getCommitMessage(
    commitJobId,
    commitStatusQuery.data?.status,
    commitStatusQuery.data?.errorMessage,
    commitMutation.error,
  );

  return {
    selectedDate,
    setSelectedDate,
    selectedSummaryId,
    setSelectedSummaryId,
    title,
    setTitle,
    draft,
    setDraft,
    tilList,
    selectedTil,
    tilQuery,
    recallCardsQuery,
    sourcesQuery,
    generationStatusQuery,
    commitStatusQuery,
    generateMutation,
    updateMutation,
    deleteMutation,
    commitMutation,
    generationTone,
    commitTone,
    generationMessage,
    commitMessage,
  };
}

function getLatestAutoGeneratedTilDate() {
  const date = new Date();
  date.setDate(date.getDate() - (date.getHours() < 3 ? 2 : 1));
  return formatDate(date);
}

function getInitialSelectedDate() {
  if (typeof window === 'undefined') return getTodayDate();

  const dateParam = new URLSearchParams(window.location.search).get('date');
  return isValidDateParam(dateParam) ? dateParam : getTodayDate();
}

function getGenerationJobStorageKey(targetDate: string) {
  const sessionId = typeof window === 'undefined'
    ? null
    : window.localStorage.getItem(SESSION_ID_STORAGE_KEY);
  return `${TIL_GENERATION_JOB_STORAGE_PREFIX}:${sessionId ?? 'anonymous'}:${targetDate}`;
}

function getStoredGenerationJobId(targetDate: string) {
  if (typeof window === 'undefined') return null;
  return window.sessionStorage.getItem(getGenerationJobStorageKey(targetDate));
}

function storeGenerationJobId(targetDate: string, jobId: string) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.setItem(getGenerationJobStorageKey(targetDate), jobId);
}

function clearStoredGenerationJobId(targetDate: string) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.removeItem(getGenerationJobStorageKey(targetDate));
}

function getTodayDate() {
  return formatDate(new Date());
}

function getMillisecondsUntilNextTilBoundary() {
  const now = new Date();
  const nextBoundary = new Date(now);
  nextBoundary.setHours(3, 0, 0, 0);
  if (now >= nextBoundary) {
    nextBoundary.setDate(nextBoundary.getDate() + 1);
  }
  return nextBoundary.getTime() - now.getTime();
}

function formatDate(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function isValidDateParam(value: string | null): value is string {
  if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;

  const [year, month, day] = value.split('-').map(Number);
  const date = new Date(year, month - 1, day);

  return !Number.isNaN(date.getTime()) && formatDate(date) === value;
}

function isRunning(status?: string) {
  return status === 'PENDING' || status === 'PROCESSING';
}

function getJobTone(
  jobId: string | null,
  status: string | undefined,
  isPending: boolean,
  isError: boolean,
): TilJobTone {
  if (isError) return 'error';
  if (isPending || isRunning(status)) return 'pending';
  if (jobId && status === 'COMPLETED') return 'success';
  return 'idle';
}

function getTilGenerationErrorMessage(error: unknown) {
  return getApiErrorMessage(error, 'TIL generation request failed.', TIL_GENERATION_ERROR_MESSAGES);
}

function getGenerationMessage(
  jobId: string | null,
  status: string | undefined,
  errorMessage: string | null | undefined,
  error: unknown,
) {
  if (error) return getTilGenerationErrorMessage(error);
  if (error) return getApiErrorMessage(error, 'TIL 생성 요청에 실패했습니다.');
  if (status === 'FAILED') return errorMessage ?? 'TIL 생성 작업이 실패했습니다.';
  if (status === 'COMPLETED') return 'TIL 생성이 완료되었습니다.';
  if (status === 'PROCESSING') return 'AI가 TIL을 생성하고 있습니다.';
  if (status === 'PENDING' || jobId) return 'TIL 생성 작업이 등록되었습니다.';
  return null;
}

function getCommitMessage(
  jobId: string | null,
  status: string | undefined,
  errorMessage: string | null | undefined,
  error: unknown,
) {
  if (error) return getApiErrorMessage(error, 'GitHub 커밋 요청에 실패했습니다.');
  if (status === 'FAILED') return errorMessage ?? 'GitHub 커밋 작업이 실패했습니다.';
  if (status === 'COMPLETED') return 'GitHub 커밋이 완료되었습니다.';
  if (status === 'PROCESSING') return 'GitHub 커밋을 처리하고 있습니다.';
  if (status === 'PENDING' || jobId) return 'GitHub 커밋 작업이 등록되었습니다.';
  return null;
}
